{{- if .Values.mariadb.deploy_db }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wavelog.fullname" . }}-db
  labels:
    {{- include "wavelog.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.username | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | required "mariadb.password is required when mariadb.deploy_db=true" | quote }}
{{- end }}
